config/routes.rb
Rails.application.routes.draw do
  get 'room/index'

  root 'home#index'
  get 'home/index'

  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/logout' => 'sessions#destroy', :as => :logout
  post '/registry/register', :to => 'registry#register'
  get '/registry/setting', :to => 'registry#setting', as: :setting
  get '/registry/index', :to => 'registry#index'
  post '/create_room', :to => 'home#create_room'
  get '/destroy_room', :to => 'home#destroy_room'
  get '/room/:room_id', :to => 'room#index'
  get '/home/room_table', :to => 'home#room_table'

end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
    def self.create_with_omniauth(auth)
        create! do |user|
            user.provider = auth['provider']
            user.uid = auth['uid']

            user.name = auth['name']
            user.session_id = SecureRandom.uuid()
            user.user_id = SecureRandom.uuid()
            user.activated = false
        end
    end

    def self.find_user(provider, uid)
        User.find_by(provider: provider, uid: uid)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    helper_method :current_user

    def current_user
        if cookies[:session_id]
            @current_user ||= User.find_by(:session_id => cookies[:session_id])
        end
        @current_user
    end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
    protect_from_forgery

    def login_required
        @current_user ||= User.find_by(:session_id => cookies[:session_id])

        if not (@current_user && @current_user.activated)
            redirect_to root_path
        end
    end
end

app/controllers/catan_room_controller.rb
require 'json'
require 'catan/room'
require 'securerandom'

# key: room_id, value: room
$rooms ||= { }

# key: user_id, value: room
$user_map ||= { }

# key: user_id, value: room
$owner_map ||= { }

class CatanRoomController < WebsocketRails::BaseController
    def self.create_room(name, pass, owner_user_id, owner_name)
        room = Room.new(name, pass, owner_user_id, owner_name)
        room_id = room.room_id
        $rooms[room_id] = room
        $owner_map[owner_user_id] = room

        room_id
    end

    def self.destroy_owning_room(user_id)
        room = $owner_map[user_id]

        return unless (room && room.owner_user_id == user_id)

        room_members = room.room_members
        room_members.each {|x|
            $user_map.delete(x.user_id)
            x.close!
        }

        $rooms.delete room.room_id
        $owner_map.delete user_id
    end

    def self.has_own_room?(user_id)
        !!$owner_map[user_id]
    end

    # Returns [user_id, room]
    def get_user_info(session_id)
      user_id = User.find_by(session_id: session_id).user_id
      room = $user_map[user_id]
      [user_id, room]
    end

    def join_receive
        room_id = message['room_id']
        session_id = message['session_id']
        user_id = User.find_by(session_id: session_id).user_id

        room = $rooms[room_id]
        return unless room

        pass = room.password
        if room.owner_user_id == user_id or pass == nil or pass == ''
            $user_map[user_id] = room
            room.add_member(user_id, session_id)
        elsif not message['password']
            send_message :password_required, {}
        elsif pass != message['password']
            connection.close!
        else
            $user_map[user_id] = room
            room.add_member(user_id, session_id)
        end
    end

    def command_receive
        session_id = connection.user_identifier
        user_id, room = get_user_info session_id

        return unless room

        begin
            room.on_receiving_command session_id, message
        rescue => e
            byebug
        end
    end

    def chat_receive
        session_id = connection.user_identifier
        user_id, room = get_user_info session_id

        return unless room

        room.on_receiving_chat session_id, message
    end

    def disconnected
        session_id = connection.user_identifier
        user_id, room = get_user_info session_id

        $user_map.delete(user_id)
        need_to_delete_room = room.remove_member session_id
        if need_to_delete_room
            CatanRoomController.destroy_owning_room room.owner_user_id
        end
    end

    def player_list_changed
        session_id = connection.user_identifier
        user_id, room = get_user_info session_id

        return unless room && user_id == room.owner_user_id

        room.change_player_list message['player_list'], message['not_player_list']
    end

    def start_button_clicked
        session_id = connection.user_identifier
        user_id, room = get_user_info session_id

        return unless room && user_id == room.owner_user_id

        room.game_start
    end

    def transfer_authority
        session_id = connection.user_identifier
        user_id, room = get_user_info session_id
        new_owner_id = message['user_id']

        return if $owner_map[new_owner_id] || user_id != room.owner_user_id

        return unless room.transfer_authority message['user_id']
        $owner_map.delete user_id
        $owner_map[new_owner_id] = room
    end

    def dice_1d100
        session_id = connection.user_identifier
        user_id, room = get_user_info session_id

        return unless room

        room.dice_1d100 session_id
    end
end

app/controllers/home_controller.rb
class HomeController < BaseController
    def index
    end

    def create_room
        name = params[:name]
        pass = params[:pass]

        if current_user && !$owner_map[current_user.user_id]
            room_id = CatanRoomController.create_room(name, pass, current_user.user_id, current_user.name)
            redirect_to "/room/#{room_id}"
        else
            redirect_to root_path
        end
    end

    def destroy_room
        if current_user
            CatanRoomController.destroy_owning_room(current_user.user_id)
        end
        redirect_to root_path
    end

    def room_table
        render layout: false
    end
end

app/controllers/registry_controller.rb
class RegistryController < ApplicationController
    protect_from_forgery

    def login_required
        @current_user ||= User.find_by(:session_id => cookies[:session_id])

        if not @current_user
            redirect_to root_path
        end
    end

    def index
    end

    def settings
    end

    def register
        current_user.update(name: params[:name], activated: true)

        cookies[:name] = params[:name]
        redirect_to root_path
    end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  def index
      unless room
          redirect_to root_path
          return
      end
  end

  helper_method :room_id, :room, :is_room_owner
  private
  def room_id
      @room_id ||= params[:room_id]
  end

  def room
      @room ||= $rooms[room_id]
  end

  def is_room_owner
      current_user && (CatanRoomController.has_own_room? current_user.user_id)
  end
end

app/controllers/sessions_controller.rb
require 'securerandom'

class SessionsController < ApplicationController
    def gen_session_id
        SecureRandom.uuid()
    end

    def callback
        auth = request.env['omniauth.auth']

        provider = auth['provider']
        uid = auth['uid']

        user = User.find_user(provider, uid)
        session_id = gen_session_id()

        if not user
            user = User.create_with_omniauth(auth)
            user.update(session_id: session_id)
            cookies[:session_id] = session_id
            redirect_to registry_index_path
        elsif not user.activated
            user.update(session_id: session_id)
            cookies[:session_id] = session_id
            redirect_to registry_index_path
        else
            user.update(session_id: session_id)
            cookies[:session_id] = session_id
            cookies[:name] = user.name
            redirect_to root_path
        end
    end

    def destroy
        cookies[:session_id] = nil
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registry_helper.rb
module RegistryHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div id='room_info_area' class='main_section'>
  <div id='room_control_area'>
    <% if current_user %>
      <% if $owner_map[current_user.user_id] %>
        <a id='delete_room_button' href='/destroy_room' class='anchor_button'>自分の部屋を削除する</a>
      <% else %>
        <a id='new_room_button' href='javascript:show_new_room_form()' class='anchor_button'>新しい部屋を作る</a>
      <% end %>
    <% end %>
  </div>
  <table id='room_table'>
    <thead id='room_table_header'>
      <tr>
        <th></th>
        <th>部屋名</th>
        <th>ルームマスター</th>
        <th>参加人数</th>
        <th>状態</th>
      </tr>
    </thead>
    <tbody id='room_table_body'>
    </tbody>
  </table>
</div>

<div id='description_area', class='main_section'>
    <h2>Online Catanへようこそ。</h2>
    <p>このサイトでは、Twitterのアカウントを利用して、「カタンの開拓者たち」風のゲームを遊ぶことができます。</p>
    <p>最新のブラウザでご利用ください！<br/>(HTML5 canvas, websocket, CSS3を使用しています)</p>
</div>

<div id='new_room_screen'>
    <div id='new_room_form'>
        <h1>新しい部屋を作る</h1>
        <hr/>
        <%= form_tag('/create_room') { %>
            <div>
                <%= label_tag 'name', '部屋名', class: 'before_box' %>
                <%= text_field_tag 'name' %>
            </div>
            <div>
                <div>
                    <%= check_box_tag 'has_pass', '1', false, id: 'has_pass_checkbox' %>
                    <%= label_tag 'has_pass_checkbox', 'パスワードを設定する', class: 'after_box' %>
                </div>
                <div>
                    <%= label_tag 'pass', 'パスワード', class: 'before_box' %>
                    <%= text_field_tag 'pass', '', id: 'pass_textbox', disabled: true %>
                </div>
            </div>
            <div id='button_area'>
                <%= button_tag 'キャンセル', type: 'button', onclick:'javascript:hide_new_room_form()', class:'anchor_button' %>
                <%= submit_tag '作成', class: 'anchor_button' %>
            </div>
        <% } %>
    </div>
</div>

app/views/home/room_table.html.erb
<% $rooms.each { |k, v| %>
  <tr>
    <td>
      <% if v.password and v.password != '' %>
        <img src='/images/locked_icon.png' class='room_locked_icon' />
      <% else %>
        <img src='/images/unlocked_icon.png' class='room_locked_icon' />
      <% end %>
    </td>
    <td><%= v.name %></td>
    <td><%= v.owner_name %></td>
    <td><%= v.room_members.length %></td>
    <td>
      <% if v.is_playing %>
        プレイ中
      <% else %>
        待機中
      <% end %>
    </td>
    <% if current_user %>
      <td><%= link_to '参加', "/room/#{ v.room_id }", class: 'anchor_button' %></td>
    <% end %>
  </tr>
<% } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Catan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Catan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='header'>
    <div id='logo_area'>
        <h1>Online Catan</h1>
    </div>
    <div id='login_area'>
        <% if current_user %>
            <%= current_user.name %>
            <%= link_to 'アカウント設定', setting_path %>
            <%= link_to 'ログアウト', logout_path %>
        <% else %>
            <%= link_to 'ログイン', '/auth/twitter' %>
        <% end %>
    </div>
</div>
<div id='content'>
    <%= yield %>
</div>
<div id='footer'>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Catan</title>
  <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='header'>
    <div id='header_inner'>
        <div id='logo_area'>Online Catan</div>
        <div id='login_area'>
            <div id='login_area_inner'>
                <% if current_user %>
                    <%= current_user.name %>
                    <%= link_to 'アカウント設定', setting_path, class: 'anchor_button' %>
                    <%= link_to 'ログアウト', logout_path, class: 'anchor_button', id: 'loginout_button' %>
                <% else %>
                    <%= link_to 'ログイン', '/auth/twitter', class: 'anchor_button', id: 'loginout_button' %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div id='content'>
    <%= yield %>
</div>
<div id='footer'>
</div>

</body>
</html>

app/views/layouts/registry.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Catan</title>
  <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'registry', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='header'>
    <div id='logo_area'>Online Catan</div>
</div>

<div id='content'>
    <%= yield %>
</div>

<div id='footer'>
</div>

</body>
</html>

app/views/layouts/room.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Catan</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:900,500,100,300,700|Roboto+Condensed:700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'room', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'room', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/registry/index.html.erb
<div id='description_area', class='main_section'>
    <h1>ようこそ</h1>
    <div>
        ようこそ！<br/>
        アカウントは新しく作られました。必要な情報を登録してください。
    </div>
    <hr/>
    <div id='registry_form'>
        <%= form_tag('/registry/register') { %>
            <div>
                <%= label_tag 'name', 'ユーザー名', class: 'before_box' %>
                <%= text_field_tag 'name', current_user.name %>
            </div>
            <div id='button_area'>
                <%= submit_tag '登録', class: 'anchor_button' %>
            </div>
        <% } %>
    </div>
</div>

app/views/registry/setting.html.erb
<div id='description_area', class='main_section'>
    <h1>アカウント情報変更</h1>
    <div>
        アカウントの情報を変更できます。
    </div>
    <hr/>
    <div id='change_form'>
        <%= form_tag('/registry/register') { %>
            <div>
                <%= label_tag 'name', 'ユーザー名', class: 'before_box' %>
                <%= text_field_tag 'name', current_user.name %>
            </div>
            <div id='button_area'>
                <%= submit_tag '変更', class: 'anchor_button' %>
            </div>
        <% } %>
    </div>
</div>

app/views/room/index.html.erb
<div id='lobby_screen'>
    <div id='header'>
        <div id='header_inner'>
            <h1 id='title'><%= room.name %></h1>
            <div id='menu'>
                <div id='menu_inner'>
                    <ul id='owner_menu' class='menu privileged_item'>
                        <li>
                            <a href="#" class='menu_top'>メニュー</a>
                            <ul>
                                <li><a href="/destroy_room">この部屋を削除</a></li>
                                <li><a href="javascript:show_authority_transfer_form()">権限を譲渡</a></li>
                                <li><a href="/">部屋を出る</a></li>
                                <li><a href="/logout">ログアウト</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul id='guest_menu' class='menu unprivileged_item'>
                        <li>
                            <a href='#' class='menu_top'>メニュー</a>
                            <ul>
                                <li><a href="/">部屋を出る</a></li>
                                <li><a href="/logout">ログアウト</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id='content'>
        <div id='leftside'>
            <div id='chat_area_l' class='main_section'>
                <h2>チャット</h2>
                <div id='chat_view_l'></div>
                <div id='chat_input_area_l'>
                    <input type='text' id='chat_textbox_l'></input>
                    <a id='diceroll' href='javascript:dice_1d100()'>
                        <img id='die_img' src='/images/die.png' />
                    </a>
                </div>
            </div>
        </div>
        <div id='rightside'>
            <div id='controlarea' class='main_section'>
                <div id='player_select_area'>
                    <div id='not_player_area'>
                        <h2>観戦者</h2>
                        <div id='not_player_list_area'>
                            <ul class='room_member_list' id='not_player_list'>
                            </ul>
                        </div>
                    </div>
                    <div id='player_area'>
                        <h2>参加者</h2>
                        <div id='player_list_area'>
                            <ul class='room_member_list' id='player_list'>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div id='start_button_area'>
                <a href='javascript:on_start_button_clicked()' class='anchor_button privileged_item'>ゲームスタート</a>
            </div>
        </div>
    </div>
</div>
<div id='playing_screen'>
    <div style="display: none">
        <img id="icon_chance" src="/resources/catan/icon_chance_1506212242.png">
        <img id="icon_resource" src="/resources/catan/icon_resource_1511042202.png">
        <img id="icon_land" src="/resources/catan/icon_land_1507012141.png">
        <img id="land_edge" src="/resources/catan/land_edge_withP_1508152147.png">
        <img id="font_land" src="/resources/catan/font_land_1507052218.png">
        <img id="board_object" src="/resources/catan/structures_1507082305.png">
        <img id='icon_button' src='/resources/catan/icon_button_1511082227.png'>
        <img id='trade_button_clear' src='/resources/catan/trade_button_clear.png'>
        <img id='trade_base' src='/resources/catan/trade_oversea_1508162228.png'>
        <img id='trade_base_clear' src='/resources/catan/trade_base_clear_1508111027.png'>
        <img id='spinbox_button' src='/resources/catan/spinbox_button.png'>
        <img id='trade_form_decide_button' src='/resources/catan/trade_form_decide_button.png'>
        <img id='trade_button_mousedown' src='/resources/catan/trade_button_1508112337.png'>
        <img id='icon_robber' src='/resources/catan/icon_robber_1508162130.png'>
        <img id='trade_player_base' src='/resources/catan/trade_player_1508162206.png'>
        <img id='trade_confirm_button' src='/resources/catan/trade_alternative_button_1508162259.png'>
        <img id='icon_chance_card' src='/resources/catan/ChanceCard_1508160030.png'>
        <img id='icon_dice' src='/resources/catan/icon_dice_1508192321.png'>
        <img id='harvest_form' src='/resources/catan/harvest_1508222150.png'>
        <img id='monopoly_form' src='/resources/catan/monopoly_1508222151.png'>
        <img id='robber_screen' src='/resources/catan/robber_screen_1508282248.png'>
        <img id='burst_form' src='/resources/catan/burst_1508282208.png'>
        <img id='burst_button' src='/resources/catan/burst_button_1508282208.png'>
        <img id='chance_used' src='/resources/catan/chance_used_1509030000.png'>
        <img id='chance_available' src='/resources/catan/chance_available_1509022317.png'>
        <img id='special_card' src='/resources/catan/special_1509022338.png'>
        <img id='chance_other_used' src='/resources/catan/chance_otherused_1509022358.png'>
        <img id='victory_screen' src='/resources/catan/victory_screen_1509030028.png'>
        <img id='resource_amount' src='/resources/catan/resource_amount_1511160001.png'>
        <img id='burst_screen' src='/resources/catan/burst_screen_1512132153.png'>
        <audio id='notification_sound' src='/resources/catan/notification.mp3'>
        <audio id='notification_sound2' src='/resources/catan/notification2.mp3'>
        <audio id='notification_sound3' src='/resources/catan/notification3.mp3'>
        <audio id='notification_sound4' src='/resources/catan/notification4.mp3'>
    </div>
    <div id='board_container'>
        <canvas id="board" width='960' height='704'></canvas>
        <div id='systemlog_area' class='log_area'></div>
        <div id='chat_area' class='log_area'></div>
        <input type="text" id='chat_textbox'>
        <div id='hint_area'></div>
        <input type='button' id='back_button' text='待機画面に戻る'>
        <canvas id='overlay' width='960' height='280' style="display: none"></canvas>
    </div>
</div>
<div id='authority_transfer_screen'>
    <div id='authority_transfer_form'>
        <div id='at_new_owner_list'>
        </div>
        <div id='at_button_area'>
            <input type='button' id='transfer_authority_button' value='譲渡する' onclick='transfer_authority()'>
            <input type='button' value='キャンセル' onclick='hide_authority_transfer_form()'>
        </div>
    </div>
</div>
<div id='loading_screen'>
    <div id='loading_message1'>
        <div id='loading_message2'>
            Loading...<img src='/images/loading.gif'>
        </div>
    </div>
</div>